# Python para la Ciencia de Datos - Taller 3

Fecha: **15/05/2024**

Autor: **MSc. Ing. CIP Francisco Cerna**

Objetivo:

Desarrollar los ejercicios prácticos en el lenguaje de programación Python.

Documentación oficial:


1.   [docs.python.org](https://docs.python.org/3/tutorial/)




In [3]:
!python --version

Python 3.10.12


In [4]:
import warnings
warnings.simplefilter("ignore")

## Parte 3: Funciones en Python




Las funciones en Python utilizan la palabra reservada `def` antes de colocar el nombre de la función.



```
def nombre_de_la_funcion(nombre_argumento):
    # Lógica de la función.
```

Ejemplo:

```
def sumar(numero_1, numero_2):
    resultado = numero_1 + numero_2
    print(resultado)
```




In [5]:
def mostrar_nombre(nombre=""):
  print(nombre.upper())

In [6]:
mostrar_nombre(nombre="Hola a todos")

HOLA A TODOS


### Pregunta 1:

Crear una función llamada `saludo`. La función debe de recibir una variable llamada `nombre`. La función debe mostrar el nombre ingresado utilizando la función `print()`.

In [7]:
def saludo(nombre=""):
  print(nombre)

saludo("Juan Carlos")

Juan Carlos


### Pregunta 2:

Crear una función llamada `saludo`. La función debe de recibir una variable llamada `nombre`. La función debe mostrar el nombre ingresado utilizando la función `print()`. La función debe retornar la palabra `"Buenos días, "` concatenado del nombre ingresado.

In [8]:
def saludo(nombre=""):
  print(f'Buenos días, {nombre}.')

saludo("Juan Carlos")

Buenos días, Juan Carlos.


### Pregunta 3:

### Importar librerías

Utilizaremos la librería NumPy para manipular datos.

[Documentación de NumPy](https://numpy.org/doc/stable/user/absolute_beginners.html).

Importar la librería NumPy. Para ello, se debe de ejecutar el siguiente código:

El estándar del uso de NumPy es colocarle un alias llamado `np`.

```
import numpy as np
```

Una función que ofrece la librería es obtener el promedio o media artimética de una lista.

Entonces, debes obtener el promedio de la lista usando la función `mean()`.

Toma como referencia la documentación del [enlace](https://numpy.org/doc/stable/reference/generated/numpy.mean.html#numpy.mean).


In [9]:
import numpy as np

x = [1, 90, 8, 75, 0]

x_mean = np.mean(x) # <---- AQUI DEBES COLOCAR TU SOLUCIÓN
print(x_mean)

34.8


### Pregunta 4:

A partir de la lista anterior, debes obtener la desviación estándar de la lista.

Toma como referencia la documentación del [enlace](https://numpy.org/doc/stable/reference/generated/numpy.std.html#numpy.std).

In [10]:
x_std =  np.std(x) # <---- AQUI DEBES COLOCAR TU SOLUCIÓN
print(x_std)

39.331412382471086


### Pregunta 5:

¿Cuál es la media de la siguiente lista?

Utiliza la función `mean()` de NumPy.

In [11]:
x = [1, 1, 1, 1, 0.8]

x_mean =  np.mean(x) # <---- AQUI DEBES COLOCAR TU SOLUCIÓN
print(x_mean)

0.96


### Pregunta 6:

¿Cuál es la desviación estándar de la lista anterior?

In [12]:
x_std =  np.std(x) # <---- AQUI DEBES COLOCAR TU SOLUCIÓN
print(x_std)

0.07999999999999999


### Pregunta 7:

¿Qué diferencia encuentras entre la media de la pregunta 3 y el resultado de la pregunta 5?

¿A qué crees que se deba la diferencia de resultados?

**Respuesta:**
En que el de la pregunta 5 es un valor menos disgregado porque los valores de la lista son muy cercanos. La diferencia se debe a los valores de cada lista.

### Pregunta 8:

¿Qué diferencia encuentras entre la desviación estándar de la pregunta 4 y el resultado de la pregunta 6?

¿A qué crees que se deba la diferencia de resultados?

**Respuesta:**
El valor es demasiado lejano y se debe a que los valores están muy disgregados.

### Pregunta 9:

Crea una función que recibe como argumento una lista. La lista debe tener al menos 1 elemento. Si la lista no tiene elementos, entonces mostrar el mensaje `"La lista no tiene elementos"` y utilizar la función `print()`.

Por el contrario, si la lista tiene al menos un elemento, entonces obtener el promedio y la desviación estándar.

La función debe retornar el promedio y la desviación estándar.

In [13]:
def mostrar_lista(lista: list):
  if not lista:
    print("La lista no tiene elementos")
  if len(lista) >= 1:
    promedio = np.mean(lista)
    desviacion = np.std(lista)
    return promedio, desviacion

mostrar_lista(lista=[1, 1, 1, 1, 0.8])
#mostrar_lista(lista=[])

(0.96, 0.07999999999999999)

### Pregunta 10:

Crea una función que retorne los dos últimos elementos de una lista.

🚨 La función debe validar que la lista es diferente a `None`.

🚨 La función debe validar que la lista debe tener al menos dos elementos.

In [14]:
x

[1, 1, 1, 1, 0.8]

In [17]:
def mostrar_dos_ultimos(lista: list):
  if lista != None:
    if len(lista) < 2:
      print("La lista debe tener al menos dos elementos")
    else:
      print(lista[-2:])

#mostrar_dos_ultimos(None)
mostrar_dos_ultimos([1])
mostrar_dos_ultimos(x)

La lista debe tener al menos dos elementos
[1, 0.8]


### Tipo de dato del arreglo

En NumPy se pueden crear arreglos. Los arreglos no son listas.

Las ventajas de los arreglos son:

1.   Almacena elementos del mismo tipo de dato, lo que permite un uso más optimizado de la memoria en comparación con las listas de Python que pueden contener elementos de distintos tipos.
2.   Permite operaciones vectoriales sobre todos los elementos del arreglo a la vez. El tiempo de procesamiento es mucho más rápido en comparación con los ciclos tradicionales de Python para iterar sobre listas.
3.   Los arreglos pueden tener múltiples dimensiones, representando estructuras como matrices.

Ejemplo:



```
# Vector o Tensor de rango 1
a1D = np.array([1, 2, 3, 4])

# Matriz o Tensor de rango 2
a2D = np.array([[1, 2], [3, 4]])

# Tensor de rango 3
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```



In [18]:
# Vector o Tensor de rango 1
a1D = np.array([1, 2, 3, 4])

# Matriz o Tensor de rango 2
a2D = np.array([[1, 2], [3, 4]])

# Tensor de rango 3
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Ejecutar las siguientes celdas de código y visualizar el tipo de datos que aparece.

In [19]:
a1D.dtype

dtype('int64')

In [20]:
a2D.dtype

dtype('int64')

In [21]:
a3D.dtype

dtype('int64')

### Pregunta 11:

Crear un arreglo con el tipo de dato `np.int8`. Este valor se asigna al argumento `dtype`.


Ejemplo para crear un arreglo con `dtype`.

```
arreglo = np.array([127, 128, 129], dtype=np.uint32)
arreglo
```



¿El resultado es el mismo que el que declaraste previamente?

In [22]:
a = np.array([127, 128, 129], dtype=np.int8)
a

array([ 127, -128, -127], dtype=int8)

### Pregunta 12:

Crear un arreglo con `dtype` igual a `np.uint32`.

¿Cambiaron los valores del arreglo?

In [23]:
a = np.array([127, 128, 129], dtype=np.uint32)
a

array([127, 128, 129], dtype=uint32)

No cambian sus valores

### Pregunta 13:

Ejecutar la siguiente línea de código.

¿Qué aprecias en la matriz que creaste? ¿Qué valores aparecen en la matriz?

In [24]:
np.eye(3) # Matriz de identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Coloca acá tu respuesta
# La matriz de identidad encontrada solo tiene valores 1 en su diagonal.



### Pregunta 14:

La siguiente celda de código crea un arreglo con diferentes tipos de datos.

Además, asignamos el tipo de dato para cada dimensión del arreglo.

In [26]:
x = np.array([('Regresión lineal', 1, 0.9051), ('KNN', 2, 0.9101)],
             dtype=[('name', 'U10'), ('age', np.int8), ('weight', np.float32)])

Ejecuta las siguientes celdas de código.

¿Qué logras apreciar?

In [27]:
x['name']

array(['Regresión ', 'KNN'], dtype='<U10')

In [28]:
x['age']

array([1, 2], dtype=int8)

In [29]:
x['weight']

array([0.9051, 0.9101], dtype=float32)

In [30]:
x.dtype

dtype([('name', '<U10'), ('age', 'i1'), ('weight', '<f4')])

In [31]:
np.dtype(x.dtype)

dtype([('name', '<U10'), ('age', 'i1'), ('weight', '<f4')])

In [32]:
# Coloca acá tu respuesta

# Se puede consultar las columnas y obtener sus valores. Los tipos de datos van desde el <U10 para el string, i1 para el entero y el <f4 para un flotante.